liip_imagine:
    driver: 'gd'
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        medium:
            quality: 85
            filters:
                relative_resize: { widen: 800 }
