# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
       my_provider: 
            entity:
                class: App\Entity\User
                property: email
       app_user_provider:
          entity:
             class: App\Entity\User
             property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: main
                provider: my_provider
            logout:
                path: app_logout
                target: main

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_HOTE, ROLE_EMPLOYE, ROLE_EMPLOYE] }
        - { path: ^/back/office, roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/hote, roles: ROLE_HOTE }
        - { path: ^/profil, roles: ROLE_USER }

    
    role_hierarchy:
        ROLE_EMPLOYE: ROLE_USER
        ROLE_ADMIN: ROLE_EMPLOYE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

