%YAML 1.1
---
# ventalis.booking
-
  id: 2
  start_date: "2023-07-12"
  end_date: "2023-08-24"
  guest_count: 3
  total_price: 896
  booking_id: 1
# ventalis.doctrine_migration_versions
-
  version: "DoctrineMigrations\\Version20230718104424"
  executed_at: "2023-07-18 12:44:38"
  execution_time: 37
-
  version: "DoctrineMigrations\\Version20230718105219"
  executed_at: "2023-07-18 12:52:26"
  execution_time: 19
-
  version: "DoctrineMigrations\\Version20230719081445"
  executed_at: "2023-07-19 10:14:58"
  execution_time: 358
-
  version: "DoctrineMigrations\\Version20230720092720"
  executed_at: "2023-07-20 11:27:29"
  execution_time: 81
-
  version: "DoctrineMigrations\\Version20230720093715"
  executed_at: "2023-07-20 11:37:23"
  execution_time: 70
-
  version: "DoctrineMigrations\\Version20230720100051"
  executed_at: "2023-07-20 12:00:58"
  execution_time: 18
-
  version: "DoctrineMigrations\\Version20230720122606"
  executed_at: "2023-07-20 14:26:15"
  execution_time: 35
-
  version: "DoctrineMigrations\\Version20230720130528"
  executed_at: "2023-07-20 15:05:38"
  execution_time: 236
-
  version: "DoctrineMigrations\\Version20230720133022"
  executed_at: "2023-07-20 15:30:30"
  execution_time: 298
-
  version: "DoctrineMigrations\\Version20230720142736"
  executed_at: "2023-07-20 16:27:44"
  execution_time: 45
-
  version: "DoctrineMigrations\\Version20230720144317"
  executed_at: "2023-07-20 16:43:31"
  execution_time: 56
-
  version: "DoctrineMigrations\\Version20230720144819"
  executed_at: "2023-07-20 16:48:29"
  execution_time: 38
# ventalis.logements
-
  id: 2
  title: "Casa na montanha, ski et snowboard liberado !"
  description: "Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !Casa na montanha, ski et snowboard liberado !"
  price: 500
  availability: "2023-09-13"
# ventalis.messages
-
  id: 1
  content: "sabe qual muito bom arruma essa parada ai rapaz.sab essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz.sabe qual muito bom arruma essa parada ai rapaz."
  timestamp: "2023-09-14 17:37:54"
# ventalis.panier_product
-
  panier_id: null
  product_id: 35
  id: 3
  quantity: 1
# ventalis.product
-
  id: 34
  name: "Ordinateur"
  prix: 4444
  description: "ordinateur"
  valide: "1"
  stock: 6
-
  id: 35
  name: "Macbook"
  prix: 4444
  description: "MacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbookMacbook"
  valide: "1"
  stock: 1
-
  id: 36
  name: "Iphone"
  prix: 444
  description: "IphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphoneIphone"
  valide: "1"
  stock: 1
-
  id: 37
  name: "TELE"
  prix: 4444
  description: "La vie est une aventure passionnante, remplie de découvertes et de défis. Chaque jour apporte des opportunités et des leçons précieuses. Restons ouverts, embrassons le changement et persévérons. Avec passion et détermination, nous"
  valide: "1"
  stock: 1
-
  id: 38
  name: "Moto"
  prix: 522
  description: "Bonjour, je m'appelle Bard. Je suis un grand modèle de langage, également connu sous le nom d'IA conversationnelle ou chatbot, formé pour être informatif et complet. informatif et complet.informatif et complet.complet.complet.complet.comp"
  valide: "1"
  stock: 1
# ventalis.review
-
  id: 1
  content: "muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!muito bom !!!!!!!!"
  rating: 4
# ventalis.user
-
  id: 24
  email: "wembleydasilva@gmail.com"
  password: "$2y$13$d.irNd2enPcG4cTI0QG/E.5pkSsD4vbYNrtCZWuLe93hnrdQxP8my"
  first_name: "WEMBLEY"
  last_name: "DA SILVA"
  telephone: "wembleydasilvaee@gmail.com"
  roles: "[\"ROLE_ADMIN\"]"
-
  id: 29
  email: "leonardodicaprio@ventalis.com"
  password: "$2y$13$JgDkN/E0hIAxlXNYgRYz2.rYxKNBW4FY/50VUQNiejSO1tgVUHvOq"
  first_name: "leonardo"
  last_name: "Dicaprio"
  telephone: "06558899966"
  roles: "[\"ROLE_ADMIN\"]"
-
  id: 31
  email: "angelinajolie@ventalis.com"
  password: "$2y$13$tzEJ4A8uCdGnf8F6pax/SeDd2u3bMpptDBBuAXIAJqRUbi/4EdDnO"
  first_name: "Angelina"
  last_name: "Jolie"
  telephone: "124578963"
  roles: "[\"ROLE_HOTE\"]"
-
  id: 32
  email: "elonmusk@ventalis.com"
  password: "$2y$13$i6niqP/6d.2QNJX.Lfs0r.N1psjqr.QfD1UCZMyyDZPyeJMzrXsFa"
  first_name: "Elon"
  last_name: "Musk"
  telephone: "1245789633"
  roles: "[\"ROLE_EMPLOYE\"]"
-
  id: 33
  email: "theweekend@ventalis.com"
  password: "$2y$13$eGxbUxBpWa8gpzFW9TY/xucW6cQOzGb0FDri8gseCz228OKAStNsC"
  first_name: "The"
  last_name: "Weekend"
  telephone: "558899665544"
  roles: "[\"ROLE_EMPLOYE\",\"ROLE_USER\"]"
-
  id: 34
  email: "brucewilliams@ventalis.com"
  password: "$2y$13$CHQFK8gCMaUBnT2igVXh6.E22qJr.0cdS1tp840y4OTmmiP69U8R2"
  first_name: "Bruce"
  last_name: "Wil"
  telephone: "0644863601"
  roles: "[\"ROLE_USER\"]"
...
